spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    enabled: true
  ai:
    openai:
      base-url: ${AI_BASE_URL}
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_MODEL}
          stream: false
jwt:
  secret: ${JWT_SECRET}
