package com.tripdesigner.user;

import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.plugins.inner.OptimisticLockerInnerInterceptor;
import com.tripdesigner.common.security.JwtUtil;
import com.tripdesigner.common.security.UserContext;
import com.tripdesigner.common.security.UserContextHolder;
import com.tripdesigner.user.api.dto.UserUpdateRequest;
import com.tripdesigner.user.application.UserAppService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("local")
class UserIntegrationTest {

    @Autowired UserAppService userService;
    @Autowired JwtUtil jwt;
    @Autowired JdbcTemplate jdbc;

    @DynamicPropertySource
    static void props(DynamicPropertyRegistry r) {
        r.add("spring.datasource.url", () -> "jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH");
        r.add("spring.datasource.username", () -> "sa");
        r.add("spring.datasource.password", () -> "");
        r.add("spring.datasource.driver-class-name", () -> "org.h2.Driver");
        r.add("spring.flyway.enabled", () -> "false");
        r.add("spring.sql.init.mode", () -> "never");
        r.add("spring.data.redis.host", () -> "localhost");
        r.add("spring.data.redis.port", () -> "6379");
        r.add("app.auth.permit-paths", () -> "/auth/**,/ai/**");
    }

    @Test
    void fetch_me_and_update() {
        // 手动建表（在当前连接中）
        jdbc.execute("CREATE TABLE users (" +
            "id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "email         VARCHAR(128) NOT NULL," +
            "password_hash VARCHAR(100) NOT NULL," +
            "nickname      VARCHAR(64)," +
            "status        SMALLINT     NOT NULL DEFAULT 1," +
            "created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "version       INT          NOT NULL DEFAULT 0," +
            "CONSTRAINT uk_users_email UNIQUE (email)" +
        ")");
        jdbc.execute("CREATE INDEX idx_users_email ON users(email)");

        // 插入测试用户
        jdbc.update("INSERT INTO users (email, password_hash, nickname, status) VALUES (?, ?, ?, ?)",
            "it@b.com", "dummy", null, (short) 1);

        Long userId = jdbc.queryForObject("SELECT id FROM users WHERE email = ?", Long.class, "it@b.com");

        // 手动生成 JWT 模拟鉴权
        UserContextHolder.set(new UserContext(userId, "it@b.com"));
        try {
            assertEquals("it@b.com", userService.me().getEmail());

            UserUpdateRequest upd = new UserUpdateRequest();
            upd.setNickname("wen");
            assertEquals("wen", userService.update(upd).getNickname());

            // 验证数据库也已更新
            String nickname = jdbc.queryForObject("SELECT nickname FROM users WHERE id = ?", String.class, userId);
            assertEquals("wen", nickname);
        } finally {
            UserContextHolder.clear();
        }
    }

    @TestConfiguration
    static class TestConfig {
        @Bean
        public MybatisPlusInterceptor mybatisPlusInterceptor() {
            MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
            interceptor.addInnerInterceptor(new OptimisticLockerInnerInterceptor());
            return interceptor;
        }
    }
}